import type { Metadata } from "next";
import { Poppins  } from "next/font/google";
import "./globals.css";
import { AntdRegistry } from '@ant-design/nextjs-registry';
import { Layout } from "antd";
import Sider from "antd/es/layout/Sider";
import { Content } from "antd/es/layout/layout";
import { AppBreadcrumb, AppFooter, AppHeader, AppSideMenu } from "@/components";


const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.variable}>
        <AntdRegistry>
          <Layout>
            <AppHeader/>
            <Layout hasSider>
              <Sider
                theme="light"
                style={{
                  position: "fixed",
                  top: 64,
                  left: 0,
                  marginRight: "1px solid #f1f1f1",
                  height: "calc(100vh - 64px)"
                 }}
              >
                <AppSideMenu/>
              </Sider>
              <Layout style={{ marginLeft: 200 }}>
                <AppBreadcrumb/>
                <Content
                  style={{
                      padding: "16px",
                      minHeight: "calc(100vh - 64px)"
                    }}
                >
                  <div
                    style={{
                      padding: 24,
                      minHeight: 360,
                      background: "#ffff",
                      borderRadius: 20,
                    }}
                  >
                    {children}
                  </div>
                </Content>
                <AppFooter/>
              </Layout>
            </Layout>
          </Layout>
        </AntdRegistry>
      </body>
    </html>
  );
}
