import type { Metadata } from "next";
import { Inter } from "next/font/google";
import styles from './styles.module.css';
import { BiMenuAltLeft } from "react-icons/bi";
import { IoSearchOutline } from "react-icons/io5";
import { IoNotificationsOutline } from "react-icons/io5";
import { HiMiniUserCircle } from "react-icons/hi2";

import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <nav className={styles.nav}>
                <BiMenuAltLeft className={styles.menu} />
                <div className={styles.search}>
                    <Link href={"#"}><IoSearchOutline className={styles.icon} /></Link>
                    <input className={styles.input} type="search" name="" id="" placeholder="Buscar en Adopet" />
                </div>
                <Link href={"#"}><IoNotificationsOutline className={styles.notification} /></Link>
                <div className={styles.user}>
                    <HiMiniUserCircle className={styles.face} />
                    <h5 className={styles.name}>User</h5>
                </div>
            </nav>
        {children}
      </body>
    </html>
  );
}